#!/bin/bash

# $1 est le fichier de trace
# La file dont vous voulez tracer un graphe sur sa taille

# On utilise le script plot.sh pour tracer la courbe
#./plot.sh time_queue.dat | gnuplot > graph.png

gnuplot <<- EOF
	set xlabel "Temps (s)"
	set ylabel "Taille file d'attente"
	set title "Evolution de la cwnd"
	set terminal png
	set output "graph.png"
	plot "congestion_control.data" using 1:2 with lines title 'Lien 0->5(rtt 1)',\
	"congestion_control.data" using 1:3 with lines title 'Lien 1->5(rtt 10)',\
	"congestion_control.data" using 1:4 with lines title 'Lien 2->5(rtt 100)'
	EOF