#!/bin/bash


gnuplot <<- EOF
	set xlabel "Temps (s)"
	set ylabel "Nombre d'émissions en 0.05 s"
	set title "Echantillon du nombre de paquets émis par tranches de 0.05 s"
	set terminal png
	set output "EchantillonEmission.png"
	plot "nombrePaquetsEmisEchantillon.data" using 1:2 with lines title '1',\
	"nombrePaquetsEmisEchantillon.data" using 1:3 with lines title '2',\
	"nombrePaquetsEmisEchantillon.data" using 1:4 with lines title '3',\
	"nombrePaquetsEmisEchantillon.data" using 1:5 with lines title '4',\
	"nombrePaquetsEmisEchantillon.data" using 1:6 with lines title '5',\
	"nombrePaquetsEmisEchantillon.data" using 1:7 with lines title '6',\
	"nombrePaquetsEmisEchantillon.data" using 1:8 with lines title '7',\
	"nombrePaquetsEmisEchantillon.data" using 1:9 with lines title '8',\
	"nombrePaquetsEmisEchantillon.data" using 1:10 with lines title '9',\
	"nombrePaquetsEmisEchantillon.data" using 1:11 with lines title '10',\
	"nombrePaquetsEmisEchantillon.data" using 1:12 with lines title '11',\
	"nombrePaquetsEmisEchantillon.data" using 1:13 with lines title '12',\
	"nombrePaquetsEmisEchantillon.data" using 1:14 with lines title '13',\
	"nombrePaquetsEmisEchantillon.data" using 1:15 with lines title '14',\
	"nombrePaquetsEmisEchantillon.data" using 1:16 with lines title '15',\
	"nombrePaquetsEmisEchantillon.data" using 1:17 with lines title '16',\
	"nombrePaquetsEmisEchantillon.data" using 1:18 with lines title '17',\
	"nombrePaquetsEmisEchantillon.data" using 1:19 with lines title '18',\
	"nombrePaquetsEmisEchantillon.data" using 1:20 with lines title '19',\
	"nombrePaquetsEmisEchantillon.data" using 1:21 with lines title '20',\
	"nombrePaquetsEmisEchantillon.data" using 1:22 with lines title '21',\
	"nombrePaquetsEmisEchantillon.data" using 1:23 with lines title '22',\
	"nombrePaquetsEmisEchantillon.data" using 1:24 with lines title '23',\
	"nombrePaquetsEmisEchantillon.data" using 1:25 with lines title '24',\
	"nombrePaquetsEmisEchantillon.data" using 1:26 with lines title '25',\
	"nombrePaquetsEmisEchantillon.data" using 1:27 with lines title '26'

	EOF